### ISSUE TITLE
raw

### ISSUE THREAD

**Issue by grinvaldsjanis** [aniawsz/rtmonoaudio2midi#3]
NameError: name 'raw_input' is not defined

**Comment by grinvaldsjanis** [comment]
AttributeError: module 'fluidsynth' has no attribute 'Synth'

**Comment by vteneva** [comment]
Hi,
I'm getting the same error message as the previous comment. When I try to run `synth.py`, I get `AttributeError: module 'fluidsynth' has no attribute 'Synth'`. Which version of fluidsynth you are using? 
Thanks in advance!

**Comment by CyxouD** [comment]
I couldn't fix second error on MacOS, but when used `fluidsynth` from `Mingus` library, it worked successfully http://bspaans.github.io/python-mingus/doc/wiki/tutorialFluidsynth.html. 
Here's PR https://github.com/aniawsz/rtmonoaudio2midi/pull/4

**Comment by CyxouD** [comment]
@grinvaldsjanis I think first error happens because your use Python3 instead of Python2

**Comment by CyxouD** [comment]
Fix in this PR https://github.com/aniawsz/rtmonoaudio2midi/pull/4

**Comment by ytneu** [comment]
@grinvaldsjanis I'm not 100% sure but it seems that you want to run python 2.x code via python3, there's no raw_input in python3, simply replace it with 'input', or run it with python 2.x

**Comment by daninovadev** [comment]
```
pip uninstall pyfluidsynth
pip install -Iv https://files.pythonhosted.org/packages/52/b0/239ec6c909d3902108824bd2fe6859b7cd51bf7a5fbe125df826fd991944/pyFluidSynth-1.3.0.tar.gz
``` 
for python 3.8
Note: using environments is suggested

**Comment by bebo609** [comment]
Traceback (most recent call last):
  File "C:\Users\body\Downloads\rtmonoaudio2midi-master\rtmonoaudio2midi-master\audiostream.py", line 6, in <module>
    from past.builtins import raw_input, xrange
  File "C:\Users\body\Downloads\rtmonoaudio2midi-master\venv\Lib\site-packages\past\builtins\__init__.py", line 43, in <module>
    from past.builtins.noniterators import (filter, map, range, reduce, zip)
  File "C:\Users\body\Downloads\rtmonoaudio2midi-master\venv\Lib\site-packages\past\builtins\noniterators.py", line 24, in <module>
    from past.types import basestring
  File "C:\Users\body\Downloads\rtmonoaudio2midi-master\venv\Lib\site-packages\past\types\__init__.py", line 25, in <module>
    from .oldstr import oldstr
  File "C:\Users\body\Downloads\rtmonoaudio2midi-master\venv\Lib\site-packages\past\types\oldstr.py", line 5, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Users\body\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
