### ISSUE TITLE
Couldn't find the FluidSynth library

### ISSUE THREAD

**Issue by lalisalala** [aniawsz/rtmonoaudio2midi#6]
Hi, I tried this code with the changes that were recommended using mingus 0.6.0 instead of pyfluidsynth.
but unfortunately it comes with a error saying: 

C:\Users\Lisa\PycharmProjects\untitled1\venv1\Scripts\python.exe C:/Users/Lisa/PycharmProjects/rtmonoaudio2midi1/audiostream.py
Traceback (most recent call last):
  File "C:/Users/Lisa/PycharmProjects/rtmonoaudio2midi1/audiostream.py", line 15, in <module>
    from mingus.midi import fluidsynth
  File "C:\Users\Lisa\PycharmProjects\untitled1\venv1\lib\site-packages\mingus\midi\fluidsynth.py", line 37, in <module>
    from mingus.midi import pyfluidsynth as fs
  File "C:\Users\Lisa\PycharmProjects\untitled1\venv1\lib\site-packages\mingus\midi\pyfluidsynth.py", line 41, in <module>
    raise ImportError("Couldn't find the FluidSynth library.")
ImportError: Couldn't find the FluidSynth library.

Can anyone help? 
I am using PyCharm with Python 3.8 and I am fairly new to Python.

Furthermore, does anybody know, how to really run this code like Ana in her presentation? Is there any graphic interface? 

Thank you in advance

**Comment by mrviktorv** [comment]
Hey there @lalisalala! 

Don't know if it's still relevant, but I have had the same issues, and I've found a solution.
I used Pycharm with Python 2.7.18 (x32) on Windows 7 (sp1, x64).
I also used mingus 0.6.0 instead of pyfluidsynth. I followed the method described here: https://github.com/aniawsz/rtmonoaudio2midi/pull/5/commits/72308a09193438eff3910c3255b5ce5daed4b16e , except I used another .sf2 file.

Then I had the error: ImportError: Couldn't find the FluidSynth library. 
If you open this file in PyCharm: C:\....\venv\lib\site-packages\mingus\midi\pyfluidsynth.py (line 35-42) - You can see that it's searching for a fluidsynth library, so you actually need a .dll for it. That's probably because FluidSynth wasn't properly installed on the computer (downloading it with PyCharm doesn't yield good results).
I found it difficult to install FluidSynth on windows, so I found a precompiled .dll library here: https://zdoom.org/downloads#Support (there's a very old version of FluidSynth, but it worked!). I just copied it to my project directory. 

For some reason, the program couldn't identify .sf2 and .dll files, so I had to set a path to them explicitly (to make sure they are identified in correct directories), like this:
find_library("C:\Games/rtmonoaudio2midi-master/venv\Lib\site-packages\mingus\midi\libfluidsynth.dll") - this is in pyfluidsynth.py
SOUNDFONT = "C:\Games/rtmonoaudio2midi-master\GeneralUseGS.sf2" - this is in app_setup.app
Don't ask me why I put the project folder in C:\Games :))

Then I just ran "audiostream.py" in PyCharm! Boom!
It's likely that you have to install python 2.7 and run the program with it (it doesn't overwrite newer versions). This is due to the incompatibility of some modules (like pyaudio) with 3.8 or 3.7 or maybe even all python 3 versions (generally, be careful about that because sometimes python is really dependent on a chain of modules and compatibility is pain:-).

I hope this approach helps someone, good luck!

P. S. I suppose Anna runs this code in some IDE (so she can change it on the fly). PyCharm is just fine for that!
P. P. S. I'm pretty new to programming and github, sorry if my solution was hard to read or ineffective.

**Comment by jsvahn** [comment]
@lalisalala do you have the Fluidsynth library (not python) installed on your computer? 
If not: Look under *Requirements* here for how to install it https://github.com/nwhitehead/pyfluidsynth

Also, with python 3.x there are some changes needed to `audiostream.py`: 

- xrange -> range
- raw_input -> input

**Comment by carlosholivan** [comment]
Hi,
I also had this problem with fluidsynth installation in Windows.
The steps I followed were:
* Install pyfluidsynth: ``pip install git+https://github.com/0xf0f/pyfluidsynth``
* Go to the path where fluidsynth has been installed: Ex.: ``C:\ProgramData\Anaconda3\Lib\site-packages`` and open ``fluidsynth.py`` file.
* In the line of ``fluidsynth.py`` where it is written ``lib = find_library('fluidsynth')`` add  ``find_library('libfluidsynth64')``
* Now download [libfluidsynth64.dll](https://github.com/fkortsagin/Heretic-Shadow-of-the-Serpent-Riders-Windows-10/blob/master/libfluidsynth64.dll) and paste it in the path where you have fluidsynth installed: Ex.: ``C:\ProgramData\Anaconda3\Lib\site-packages``

You can test if it works by running ``python``, ``import fluidsynth`` and ``fuidsynth.Synth()`` in the Anaconda Prompt.
